from sqlalchemy import create_engine, Column, Integer, String, DateTime, Text, Boolean, Float, BigInteger, ForeignKey, DECIMAL
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from datetime import datetime

Base = declarative_base()

class Supplier(Base):
    __tablename__ = 'Supplier'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(255), nullable=False)
    supplier_name = Column(String(255), nullable=False)
    address = Column(Text, nullable=False)
    phone = Column(String(20), nullable=False)
    comments = Column(Text, nullable=False)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)

class Customer(Base):
    __tablename__ = 'Customer'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(255), nullable=False)
    customer_name = Column(String(255), nullable=False)
    address = Column(Text, nullable=False)
    phone = Column(String(20), nullable=False)
    comments = Column(Text, nullable=False)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    economic_code = Column(String(15))
    national_id = Column(String(50))
    postcode = Column(String(10))

class MaterialType(Base):
    __tablename__ = 'MaterialType'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    date = Column(DateTime, nullable=False, default=datetime.now)
    supplier_name = Column(String(255))
    material_type = Column(String(255), nullable=False)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)

class RawMaterial(Base):
    __tablename__ = 'RawMaterial'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(255), nullable=False)
    supplier_name = Column(String(255))
    material_type = Column(String(255), nullable=False)
    material_name = Column(String(255), nullable=False)
    description = Column(String(255), nullable=False)
    comments = Column(Text, nullable=False)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)

class Unit(Base):
    __tablename__ = 'Unit'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(255), nullable=False)
    date = Column(DateTime, nullable=False, default=datetime.now)
    supplier_name = Column(String(255))
    material_type = Column(String(255), nullable=False)
    unit_name = Column(String(255))
    count = Column(Float)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)

class Truck(Base):
    __tablename__ = 'Truck'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(10), nullable=False)
    location = Column(String(255), nullable=False)
    license_number = Column(String(255), nullable=False)
    driver_name = Column(String(255), nullable=False)
    driver_doc = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=False)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)

class Shipments(Base):
    __tablename__ = 'Shipments'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(255))
    location = Column(String(255))
    receive_date = Column(DateTime)
    entry_time = Column(DateTime)
    weight1_time = Column(DateTime)
    weight2_time = Column(DateTime)
    exit_time = Column(DateTime)
    shipment_type = Column(String(255))
    license_number = Column(String(255))
    customer_name = Column(String(255))
    supplier_name = Column(String(255))
    weight1 = Column(Integer)
    unload_location = Column(String(255))
    unit = Column(String(255))
    quantity = Column(Integer)
    quality = Column(String(255))
    penalty = Column(String(255))
    weight2 = Column(Integer)
    net_weight = Column(String(10))
    list_of_reels = Column(Text)
    profile_name = Column(String(255))
    width = Column(Integer)
    sales_id = Column(Integer)
    price_per_kg = Column(BigInteger)
    total_price = Column(BigInteger)
    extra_cost = Column(BigInteger)
    material_type = Column(String(255))
    material_name = Column(String(255))
    vat = Column(Integer)
    invoice_status = Column(String(255))
    payment_status = Column(String(255))
    document_info = Column(Text)
    comments = Column(Text)
    cancellation_reason = Column(Text)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    purchase_id_id = Column(BigInteger)

class Purchases(Base):
    __tablename__ = 'Purchases'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(225))
    receive_date = Column(DateTime)
    payment_date = Column(DateTime)
    license_number = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    supplier_name = Column(String(255))
    unit = Column(String(255))
    quantity = Column(Integer)
    quality = Column(String(255))
    penalty = Column(String(255))
    weight1 = Column(Integer)
    weight2 = Column(Integer)
    net_weight = Column(Integer)
    price_per_kg = Column(BigInteger)
    vat = Column(Integer)
    total_price = Column(BigInteger)
    extra_cost = Column(BigInteger)
    invoice_status = Column(String(255))
    payment_details = Column(String(255))
    invoice_number = Column(String(255))
    document_info = Column(Text)
    comments = Column(Text)
    cancellation_reason = Column(Text)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class Sales(Base):
    __tablename__ = 'Sales'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime)
    status = Column(String(255))
    payment_date = Column(DateTime)
    customer_name = Column(String(255), nullable=False)
    license_number = Column(String(255))
    list_of_reels = Column(Text)
    width = Column(Integer)
    weight1 = Column(Integer)
    weight2 = Column(Integer)
    net_weight = Column(Integer)
    price_per_kg = Column(BigInteger)
    vat = Column(Integer)
    total_price = Column(BigInteger)
    extra_cost = Column(BigInteger)
    profile_name = Column(String(255))
    invoice_status = Column(String(255))
    invoice_number = Column(String(255))
    payment_details = Column(String(255))
    document_info = Column(Text)
    comments = Column(Text)
    cancellation_reason = Column(Text)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id = Column(BigInteger)

class Products(Base):
    __tablename__ = 'Products'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    location = Column(String(255), nullable=False)
    status = Column(String(50), nullable=False)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255), nullable=False)
    width = Column(Integer, nullable=False)
    gsm = Column(Integer, nullable=False)
    length = Column(Integer, nullable=False)
    grade = Column(String(255), nullable=False)
    breaks = Column(Integer, nullable=False)
    comments = Column(Text)
    qr_code = Column(Text)
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class Consumption(Base):
    __tablename__ = 'Consumption'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(50))
    location = Column(String(255))
    receive_date = Column(DateTime)
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    unit = Column(String(255))
    reel_number = Column(String(255))
    profile_name = Column(String(255))
    grade = Column(String(255))
    comments = Column(Text)
    cancelling_reason = Column(Text)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class ConsumptionProfile(Base):
    __tablename__ = 'ConsumptionProfile'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(255), nullable=False)
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    profile_name = Column(String(255))
    supplier_name = Column(String(255), nullable=False)
    material_type = Column(String(255), nullable=False)
    material_name = Column(String(255), nullable=False)
    unit = Column(String(100), nullable=False)
    quantity = Column(DECIMAL, nullable=False)
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)

class Alert(Base):
    __tablename__ = 'Alert'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    status = Column(String(20))
    message = Column(Text, nullable=False)

class Invoice(Base):
    __tablename__ = 'Invoice'
    
    id = Column(Integer, primary_key=True)
    year = Column(Integer, nullable=False)
    month = Column(Integer, nullable=False)
    day = Column(Integer, nullable=False)
    created_at = Column(DateTime, nullable=False, default=datetime.now)
    customer_id = Column(BigInteger)
    havaleh_date = Column(DateTime)
    havaleh_generated = Column(Boolean, nullable=False, default=False)
    havaleh_serial = Column(String(255))
    is_paid = Column(Boolean, nullable=False, default=False)
    payment_date = Column(DateTime)
    sale_id = Column(BigInteger)
    shipment_id = Column(BigInteger)

class Havaleh(Base):
    __tablename__ = 'Havaleh'
    
    id = Column(Integer, primary_key=True)
    date = Column(DateTime, nullable=False, default=datetime.now)
    serial = Column(String(255), nullable=False)
    note = Column(Text)
    created_at = Column(DateTime, nullable=False, default=datetime.now)
    invoice_id = Column(BigInteger, nullable=False)

class HavalehItem(Base):
    __tablename__ = 'HavalehItem'
    
    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False)
    gsm = Column(String(50))
    width = Column(String(50))
    buyer = Column(String(255))
    quantity = Column(Integer, nullable=False)
    weight = Column(Float, nullable=False)
    havaleh_id = Column(BigInteger, nullable=False)

# Warehouse Models
class AnbarSangin(Base):
    __tablename__ = 'Anbar_Sangin'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarSalonTolid(Base):
    __tablename__ = 'Anbar_Salon_Tolid'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarParvandeh(Base):
    __tablename__ = 'Anbar_Parvandeh'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarMuhvatehKardan(Base):
    __tablename__ = 'Anbar_Muhvateh_Kardan'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarKoochak(Base):
    __tablename__ = 'Anbar_Koochak'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarKhamirKordan(Base):
    __tablename__ = 'Anbar_Khamir_Kordan'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarKhamirGhadim(Base):
    __tablename__ = 'Anbar_Khamir_Ghadim'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarAkhal(Base):
    __tablename__ = 'Anbar_Akhal'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarMuhavatehHomayoun(Base):
    __tablename__ = 'Anbar_Muhavateh_Homayoun'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class AnbarPAK(Base):
    __tablename__ = 'Anbar_PAK'
    
    id = Column(Integer, primary_key=True)
    status = Column(String(50))
    location = Column(String(255))
    date = Column(DateTime, nullable=False, default=datetime.now)
    receive_date = Column(DateTime)
    last_date = Column(DateTime)
    reel_number = Column(String(255))
    supplier_name = Column(String(255))
    material_type = Column(String(255))
    material_name = Column(String(255))
    description = Column(Text)
    width = Column(Integer)
    gsm = Column(Integer)
    length = Column(Integer)
    grade = Column(String(255))
    breaks = Column(Integer)
    comments = Column(Text)
    qr_code = Column(Text)
    unit = Column(String(255))
    profile_name = Column(String(255))
    username = Column(String(255), nullable=False)
    logs = Column(Text, nullable=False)
    shipment_id_id = Column(BigInteger)

class WeightAdjustmentLog(Base):
    __tablename__ = 'myapp_weightadjustmentlog'
    
    id = Column(Integer, primary_key=True)
    license_number = Column(String(50), nullable=False)
    username = Column(String(100), nullable=False)
    original_weight = Column(String(50), nullable=False)
    adjusted_weight = Column(String(50), nullable=False)
    timestamp = Column(DateTime, nullable=False, default=datetime.now)
    action = Column(String(50), nullable=False) 